[project]
name = "rag-doc-chatbot"
version = "0.1.0"
dependencies = [
    "streamlit[pdf]",
    "langchain==1.2.17",
    "langchain-classic",
    "langchain-text-splitters",
    "langchain-community",
    "chromadb",
    "pypdf",
    "python-dotenv",
    "langchain-openai",
    "langchain-ollama",
    "langchain_chroma",
    "tokencost",
    "fastapi",
    "uvicorn",
    "pytest"
]

[tool.setuptools]
packages = ["rag_doc_backend", "rag_doc_frontend"]

[tool.pytest.ini_options]
testpaths = ["rag_doc_backend/tests"]